// Generated by CoffeeScript 2.3.1
(function() {
  var obj;

  obj = {
    firstName: "Subroto",
    lastName: "Singh",
    fullName: function() {
      return `${this.firstName}  ${this.lastName}`;
    }
  };

  console.log(obj.fullName());

}).call(this);
