// Generated by CoffeeScript 2.3.1
(function() {
  var Employee;

  Employee = class Employee {
    constructor() {
      console.log("Instantiated a new Employee Object");
      ({
        dob: function(year = 1976, month = 7, day = 24) {
          var emp1;
          new Date(year, month, day);
          emp1 = new Employee();
          return console.log(emp1.dob());
        }
      });
    }

  };

}).call(this);
