// Generated by CoffeeScript 2.3.1
(function() {
  var http, ip, port, server;

  http = require('http');

  port = 3000;

  ip = "127.0.0.1";

  server = http.createServer(function(req, res) {
    res.writeHead(200, {
      "Content-Type": "text/plain"
    });
    setInterval(function() {});
    res.write("All work and no play makes Jack a dull boy. ");
    setTimeout(function() {});
    return res.end();
  });

  server.listen(port, ip);

  console.log(`Server running at http://${ip}:${port}/`);

}).call(this);
